spring.application.name=citizen-connect-backend

# ---------------- DATABASE (Railway MySQL) ----------------
spring.datasource.url=jdbc:mysql://switchback.proxy.rlwy.net:21941/railway
spring.datasource.username=root
spring.datasource.password=yZfVSJPnamTHiaBZsmGirBDCAMuAnolD
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---------------- JPA / HIBERNATE ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# ---------------- SERVER ----------------
server.port=${PORT:8080}

# ---------------- MAIL CONFIG ----------------
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=donipatipoojitha@gmail.com
spring.mail.password=jgdggwifluvblnur

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# IMPORTANT timeout settings
spring.mail.properties.mail.smtp.connectiontimeout=20000
spring.mail.properties.mail.smtp.timeout=20000
spring.mail.properties.mail.smtp.writetimeout=20000

# debug true only for testing
spring.mail.properties.mail.debug=true

# ---------------- ACTUATOR ----------------
management.endpoints.web.exposure.include=health,info
