spring.application.name=citizen-connect-backend

# ---------------- DATABASE ----------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ---------------- HIKARI (IMPORTANT FOR DEPLOYMENT) ----------------
spring.datasource.hikari.maximum-pool-size=2
spring.datasource.hikari.minimum-idle=0
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.connection-test-query=SELECT 1

# ---------------- JPA / HIBERNATE ----------------
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# dialect remove chesina parvaledu (auto detect avutundi)

# ---------------- SERVER ----------------
server.port=${PORT:8080}

# ---------------- ACTUATOR ----------------
management.endpoints.web.exposure.include=health,info
